# Site settings
title: Lauren Haldeman
header-img: img/home-bg.jpg
email: haldeman.lauren@gmail.com
copyright_name: Lauren Haldeman
description: "Official website of poet, writer, comic book artist & illustrator Lauren Haldeman"
baseurl: ""
url: ""
twitter_username: laurenhaldeman
github_username:  wlftn
facebook_username:  laurenhaldeman
email_username:  haldeman.lauren@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
